### ISSUE TITLE
Current development

### ISSUE THREAD

**Issue by mkeryeski** [jerbob92/boxee-meego#1]
Do you have any intent to resume development on this? I am very interested in getting it working. I currently maintain an XBMC/Kodi installer for Boxee, but want to turn it into a fully functional PC/

**Comment by jerbob92** [comment]
Hi,

I never really got this working, and also didn't work on it for a long time.

I kind of have given up on the boxee and got a Intel NUC. So no, sorry.

Kind regards,

Jeroen
Op 20 feb. 2015 22:54 schreef "mkeryeski" notifications@github.com:

**Comment by mkeryeski** [comment]
Lot of new and exciting development going on in the Boxee community (see www.boxeed.in). Let me know if you change your mind - thank you.
